name: common_widgets_flutter
description: Common Widget Flutter is a repository that manages common widgets
  like PageTitle, DateTimePicker
version: 1.5.29+58
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  breakpoint: ^1.2.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  go_router: ^14.6.3
  intl: ^0.20.1
  json_annotation: ^4.9.0
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.2
  very_good_analysis: ^7.0.0
