name: common_widgets_flutter
description: Common Widget Flutter is a repository that manages common widgets
  like PageTitle, DateTimePicker
version: 1.5.37+66
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  breakpoint: ^1.2.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.3.3+1
  flutter_animate: ^4.5.2
  go_router: ^16.2.4
  intl: ^0.20.2
  json_annotation: ^4.9.0
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  build_runner: ^2.9.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.1
  very_good_analysis: ^10.0.0
  mocktail: ^1.0.4
