name: common_widgets_flutter
description: Common Widget Flutter is a repository that manages common widgets
  like PageTitle, DateTimePicker
version: 1.4.4+23
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  material_design_icons_flutter: ^6.0.7096

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1
