name: common_widgets_flutter
description: Common Widget Flutter is a repository that manages common widgets
  like PageTitle, DateTimePicker
version: 1.5.24+53
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  go_router: ^14.2.6
  intl: ^0.19.0
  json_annotation: ^4.9.0
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0
