name: common_widgets_flutter
description: Common Widget Flutter is a repository that manages common widgets
  like PageTitle, DateTimePicker
version: 1.5.11+41
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  go_router: ^13.2.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
