name: common_widgets_flutter
description: Common Widget Flutter is a repository that manages common widgets
  like PageTitle, DateTimePicker
version: 1.3.4+13
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  intl: ^0.18.0
  jiffy: ^5.0.1
  json_annotation: ^4.8.0
  material_design_icons_flutter: ^6.0.7096
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1
